#!/usr/bin/env python3
import os
with open('fstab') as fp:
	for line in fp.readlines():
		line = line[:-1]
		os.system('mount -B /%s /sandbox/%s' % (line, line))
os.system('mount -t proc proc /sandbox/proc')
